name: plumber
base: core24
version: '3.1'
summary: Media trimmer/downloader for Linux Desktop
description: |
  Powerful Media trimmer/downloader, Video to GIF creator for Linux Desktop.

grade: stable
confinement: strict
icon: snap/gui/icon.png
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  plumber:
    command: usr/bin/plumber
    extensions: [kde-neon-6]
    desktop: usr/share/applications/plumber.desktop
    plugs:
      - audio-playback
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  application:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
    override-build: |
      craftctl default
      sed -i 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/plumber.png|' ${CRAFT_PART_INSTALL}/usr/share/applications/plumber.desktop
